#source("https://bioconductor.org/biocLite.R")
#biocLite("biomaRt")
#biocLite("org.Hs.eg.db")
require(biomaRt)
require(org.Hs.eg.db)
ensembl <- useMart("ensembl", dataset="hsapiens_gene_ensembl")
eg <- mappedkeys(org.Hs.egGO)
utr <- getSequence(id=eg, type="entrezgene", seqType="3utr", mart=ensembl)
exportFASTA(utr, "utrs.fa")
